spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false